from typing import Protocol
from uuid import UUID

from domain.entities.loadout import OwnedCharacter, OwnedDeck


class LoadoutRepository(Protocol):
    async def create_character(self, character: OwnedCharacter) -> OwnedCharacter: ...

    async def get_character(self, user_id: UUID, character_id: UUID) -> OwnedCharacter | None: ...

    async def list_characters(self, user_id: UUID) -> list[OwnedCharacter]: ...

    async def create_deck(self, deck: OwnedDeck) -> OwnedDeck: ...

    async def get_deck(self, user_id: UUID, deck_id: UUID) -> OwnedDeck | None: ...

    async def list_decks(self, user_id: UUID) -> list[OwnedDeck]: ...
